### ISSUE TITLE
Mutual TLS

### ISSUE THREAD

**Issue by amrx101** [sfackler/tokio-openssl#20]
I wanna do mutual TLS using this library.

I dont see examples of how can we supply client certs. Is Mutual TLS supported?

**Comment by fspreiss** [comment]
Because this library is based on the [openssl crate](https://github.com/sfackler/rust-openssl), the actual question is whether the openssl crate supports this. And the answer is yes: you can use the [SslAcceptorBuilder::set_verify](https://docs.rs/openssl/0.10.30/openssl/ssl/struct.SslAcceptorBuilder.html#method.set_verify) to enable client authentication.
